title: Open Leadership Map White Paper
subtitle:
email: chad@mozillafoundation.org
twitter: https://twitter.com/MozOpenLeaders
chat: https://gitter.im/mozilla/open-leadership-training
description: > # this means to ignore newlines until "baseurl:"
  Open Leadership Map White Paper. A set of principles, practices, and skills
  people can use to mobilize their communities to solve shared problems and
  achieve shared goals. This map illustrates how those principles, practices,
  and skills relate to one another.
baseurl: "/olm-whitepaper" # the subpath of your site, e.g. /blog
url: "https://mozilla.github.io" # the base hostname & protocol for your site
github:
  repo: "mozilla/olm-whitepaper"
  branch: "master"


collections:
  articles:
    output: true
    permalink: /:path/

# Build settings
markdown: kramdown

redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]